Release/781xx
harness/harness-cd-community pull request #61
Opened 2023-02-20 17:48 UTC by rkapoor10

## SUMMARY

Release 781xx of Harness CD Community Edition

### Updates 
- docker-compose.yml
- values.yaml
- README.md

### Bug Fixes
Not able to sign-up user with new installation

2023-02-21 13:58 UTC, Ompragash requested changes

2023-02-21 13:58 UTC, Ompragash commented on docker-compose/harness/README.md
> +   ![compose-up](../../static/compose-up.png)
do we really need screenshots for the basic Docker compose commands here?

2023-02-21 13:58 UTC, Ompragash commented on docker-compose/harness/README.md
> +```
Running the `docker-compose logs` command in the directory with docker-compose.yml shows all the current logs so we don't need `docker ps & logs -f <CONTAINER ID>`

2023-02-21 14:49 UTC, Ompragash commented
For the Helm installer, the `README.md` is under **helm** directory, and then a sub-directory for **harness** with `values.yaml` file inside it. 

But, for the Docker installer, the `README.md` is under `docker-compose/harness` directory.

Maybe it was mistakenly added in there initially and needs a little re-arrangement.

2023-02-21 15:35 UTC, rkapoor10 commented
> For the Helm installer, the `README.md` is under **helm** directory, and then a sub-directory for **harness** with `values.yaml` file inside it.
> 
> But, for the Docker installer, the `README.md` is under `docker-compose/harness` directory.
> 
> Maybe it was mistakenly added in there initially and needs a little re-arrangement.

We can move out README.md file one level up which is under `docker-compose/harness` directory currently to maintain consistency.

2023-02-21 17:03 UTC, Ompragash commented
> We can move out README.md file one level up which is under `docker-compose/harness` directory currently to maintain consistency.

Also, test the compose commands and make sure everything works and if required make the appropriate changes

2023-02-22 06:37 UTC, harnesspravin approved these changes
/lgtm

2023-02-22 07:39 UTC, Ompragash approved these changes

2023-02-22 07:39 UTC, merged